import { Injectable } from '@angular/core';
import * as pdfMake from 'pdfmake/build/pdfmake';
import * as pdfFonts from 'pdfmake/build/vfs_fonts';
import { Margins, TDocumentDefinitions } from 'pdfmake/interfaces';
import { WeatherInfo } from '../models/weather.interface';

(pdfMake as any).vfs = pdfFonts.pdfMake.vfs;

@Injectable({
    providedIn: 'root'
})
export class PdfService {

    constructor() { }

    downloadRouteReport(
        startingLocation: string,
        destination: string,
        date: string,
        weatherList: { location: string, weather: WeatherInfo }[],
        weatherSummary: string
    ) {

        // Create body with weather info
        const docDefinitionBody: any[] = [];

        // Table Header
        docDefinitionBody.push([
            { text: 'Location', style: 'tableHeader' },
            { text: 'Temp (°C)', style: 'tableHeader' },
            { text: 'Condition', style: 'tableHeader' },
            { text: 'Est. Arrival', style: 'tableHeader' },
            { text: 'Forecast Date', style: 'tableHeader' }
        ]);

        for (const item of weatherList) {
            docDefinitionBody.push([
                { text: item.location, style: 'tableCell' },
                { text: item.weather.temperature + '°', style: 'tableCell' },
                { text: item.weather.weatherDescription, style: 'tableCell' },
                { text: item.weather.estimatedArrival, style: 'tableCell' },
                { text: item.weather.forecastDate, style: 'tableCell' }
            ]);
        }

        // Build content array
        const content: any[] = [
            // Header
            {
                table: {
                    widths: ['*'],
                    body: [[
                        {
                            text: "Sunny Route Report",
                            style: 'mainHeader',
                            border: [false, false, false, false],
                            fillOpacity: 0.1
                        }
                    ]]
                },
                layout: 'noBorders',
                margin: [0, 0, 0, 20]
            },

            // Route Info Section
            {
                columns: [
                    {
                        width: '*',
                        stack: [
                            { text: 'FROM', style: 'label' },
                            { text: startingLocation, style: 'value' }
                        ],
                        alignment: 'left'
                    },
                    {
                        width: '*',
                        stack: [
                            { text: 'TO', style: 'label' },
                            { text: destination, style: 'value' }
                        ]
                    },
                    {
                        width: 'auto',
                        stack: [
                            { text: 'DATE', style: 'label' },
                            { text: date.split(' ')[0], style: 'value' }
                        ],
                        alignment: 'right'
                    }
                ],
                columnGap: 10,
                margin: [0, 0, 0, 20]
            }
        ];

        // Weather Summary Section (Conditional)
        if (weatherSummary) {
            content.push({
                stack: [
                    { text: 'Weather Summary', style: 'sectionHeader' },
                    {
                        text: weatherSummary,
                        style: 'summaryBox'
                    }
                ],
                margin: [0, 0, 0, 20]
            });
        }

        // Detailed Weather Table
        content.push(
            { text: 'Journey Details', style: 'sectionHeader' },
            {
                style: 'table',
                table: {
                    headerRows: 1,
                    widths: ['*', 'auto', '*', 'auto', 'auto'],
                    body: docDefinitionBody
                },
                layout: {
                    hLineWidth: (i: number, node: any) => (i === 0 || i === node.table.body.length) ? 0 : 1,
                    vLineWidth: (i: number, node: any) => 0,
                    hLineColor: (i: number, node: any) => '#E0E0E0',
                    paddingLeft: (i: number, node: any) => 10,
                    paddingRight: (i: number, node: any) => 10,
                    paddingTop: (i: number, node: any) => 10,
                    paddingBottom: (i: number, node: any) => 10,
                }
            },
            // Footer
            {
                text: 'Generated by Sunny Route • sunnyroute.netlify.app',
                style: 'footer',
                margin: [0, 30, 0, 0]
            }
        );

        // Create pdfmake dd variable
        const docDefinition: TDocumentDefinitions = {
            content: content,
            styles: {
                mainHeader: {
                    fontSize: 24,
                    bold: true,
                    color: '#37ACE3',
                    alignment: 'center',
                    margin: [0, 10, 0, 10]
                },
                sectionHeader: {
                    fontSize: 14,
                    bold: true,
                    color: '#37ACE3',
                    margin: [0, 0, 0, 10]
                },
                label: {
                    fontSize: 9,
                    color: '#888888',
                    bold: true,
                    margin: [0, 0, 0, 2]
                },
                value: {
                    fontSize: 12,
                    bold: true,
                    color: '#333333'
                },
                arrow: {
                    fontSize: 20,
                    color: '#37ACE3',
                    bold: true
                },
                summaryBox: {
                    fontSize: 11,
                    color: '#444444',
                    margin: [0, 5, 0, 5],
                    lineHeight: 1.4
                },
                table: {
                    margin: [0, 5, 0, 15]
                },
                tableHeader: {
                    bold: true,
                    fontSize: 10,
                    color: '#37ACE3',
                    fillColor: '#F8F9FA',
                    margin: [0, 5, 0, 5]
                },
                tableCell: {
                    fontSize: 10,
                    color: '#555555',
                    margin: [0, 5, 0, 5]
                },
                footer: {
                    fontSize: 9,
                    color: '#AAAAAA',
                    alignment: 'center',
                    italics: true
                }
            },
            defaultStyle: {
                font: 'Roboto'
            }
        };

        pdfMake.createPdf(docDefinition).download('SunnyRoute_Report.pdf');
    }
}
